basePath: /
consumes:
    - application/json
definitions:
    Product:
        properties:
            description:
                description: description of the product
                type: string
                x-go-name: Description
            id:
                description: the id for this product
                format: int64
                minimum: 1
                type: integer
                x-go-name: ID
            name:
                description: the name of the product
                type: string
                x-go-name: Name
            price:
                description: price of the product
                format: float
                minimum: 0
                type: number
                x-go-name: Price
            sku:
                description: product SKU
                type: string
                x-go-name: SKU
        required:
            - id
            - name
            - price
            - sku
        type: object
        x-go-package: my.org/micro/product-api/data
info:
    description: '# Documentation for Product API'
    title: of Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Returns a list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
        post:
            description: Adds a new product onto the existing list of products
            operationId: addProduct
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - products
    /products/{id}:
        delete:
            description: Removes the information from the specified product
            operationId: deleteProduct
            parameters:
                - description: The id of the product to perform operation on
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - products
        patch:
            description: Modifies the specified product, altering the specified fields
            operationId: modifyProduct
            parameters:
                - description: The id of the product to perform operation on
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - products
        put:
            description: Replaces a product with a new product
            operationId: replaceProduct
            parameters:
                - description: The id of the product to perform operation on
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContent'
            tags:
                - products
produces:
    - application/json
responses:
    noContent:
        description: ""
    productsResponse:
        description: A list of products returned in the response
        schema:
            items:
                $ref: '#/definitions/Product'
            type: array
schemes:
    - http
swagger: "2.0"
