// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ModifyProductReader is a Reader for the ModifyProduct structure.
type ModifyProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewModifyProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /products/{id}] modifyProduct", response, response.Code())
	}
}

// NewModifyProductCreated creates a ModifyProductCreated with default headers values
func NewModifyProductCreated() *ModifyProductCreated {
	return &ModifyProductCreated{}
}

/*
ModifyProductCreated describes a response with status code 201, with default header values.

ModifyProductCreated modify product created
*/
type ModifyProductCreated struct {
}

// IsSuccess returns true when this modify product created response has a 2xx status code
func (o *ModifyProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify product created response has a 3xx status code
func (o *ModifyProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify product created response has a 4xx status code
func (o *ModifyProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify product created response has a 5xx status code
func (o *ModifyProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this modify product created response a status code equal to that given
func (o *ModifyProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the modify product created response
func (o *ModifyProductCreated) Code() int {
	return 201
}

func (o *ModifyProductCreated) Error() string {
	return fmt.Sprintf("[PATCH /products/{id}][%d] modifyProductCreated ", 201)
}

func (o *ModifyProductCreated) String() string {
	return fmt.Sprintf("[PATCH /products/{id}][%d] modifyProductCreated ", 201)
}

func (o *ModifyProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
