// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewModifyProductParams creates a new ModifyProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifyProductParams() *ModifyProductParams {
	return &ModifyProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifyProductParamsWithTimeout creates a new ModifyProductParams object
// with the ability to set a timeout on a request.
func NewModifyProductParamsWithTimeout(timeout time.Duration) *ModifyProductParams {
	return &ModifyProductParams{
		timeout: timeout,
	}
}

// NewModifyProductParamsWithContext creates a new ModifyProductParams object
// with the ability to set a context for a request.
func NewModifyProductParamsWithContext(ctx context.Context) *ModifyProductParams {
	return &ModifyProductParams{
		Context: ctx,
	}
}

// NewModifyProductParamsWithHTTPClient creates a new ModifyProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifyProductParamsWithHTTPClient(client *http.Client) *ModifyProductParams {
	return &ModifyProductParams{
		HTTPClient: client,
	}
}

/*
ModifyProductParams contains all the parameters to send to the API endpoint

	for the modify product operation.

	Typically these are written to a http.Request.
*/
type ModifyProductParams struct {

	/* ID.

	   The id of the product to perform operation on

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyProductParams) WithDefaults() *ModifyProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify product params
func (o *ModifyProductParams) WithTimeout(timeout time.Duration) *ModifyProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify product params
func (o *ModifyProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify product params
func (o *ModifyProductParams) WithContext(ctx context.Context) *ModifyProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify product params
func (o *ModifyProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify product params
func (o *ModifyProductParams) WithHTTPClient(client *http.Client) *ModifyProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify product params
func (o *ModifyProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the modify product params
func (o *ModifyProductParams) WithID(id int64) *ModifyProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the modify product params
func (o *ModifyProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
