// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewReplaceProductParams creates a new ReplaceProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceProductParams() *ReplaceProductParams {
	return &ReplaceProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceProductParamsWithTimeout creates a new ReplaceProductParams object
// with the ability to set a timeout on a request.
func NewReplaceProductParamsWithTimeout(timeout time.Duration) *ReplaceProductParams {
	return &ReplaceProductParams{
		timeout: timeout,
	}
}

// NewReplaceProductParamsWithContext creates a new ReplaceProductParams object
// with the ability to set a context for a request.
func NewReplaceProductParamsWithContext(ctx context.Context) *ReplaceProductParams {
	return &ReplaceProductParams{
		Context: ctx,
	}
}

// NewReplaceProductParamsWithHTTPClient creates a new ReplaceProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceProductParamsWithHTTPClient(client *http.Client) *ReplaceProductParams {
	return &ReplaceProductParams{
		HTTPClient: client,
	}
}

/*
ReplaceProductParams contains all the parameters to send to the API endpoint

	for the replace product operation.

	Typically these are written to a http.Request.
*/
type ReplaceProductParams struct {

	/* ID.

	   The id of the product to perform operation on

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceProductParams) WithDefaults() *ReplaceProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace product params
func (o *ReplaceProductParams) WithTimeout(timeout time.Duration) *ReplaceProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace product params
func (o *ReplaceProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace product params
func (o *ReplaceProductParams) WithContext(ctx context.Context) *ReplaceProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace product params
func (o *ReplaceProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace product params
func (o *ReplaceProductParams) WithHTTPClient(client *http.Client) *ReplaceProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace product params
func (o *ReplaceProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the replace product params
func (o *ReplaceProductParams) WithID(id int64) *ReplaceProductParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace product params
func (o *ReplaceProductParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
