// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReplaceProductReader is a Reader for the ReplaceProduct structure.
type ReplaceProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewReplaceProductCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /products/{id}] replaceProduct", response, response.Code())
	}
}

// NewReplaceProductCreated creates a ReplaceProductCreated with default headers values
func NewReplaceProductCreated() *ReplaceProductCreated {
	return &ReplaceProductCreated{}
}

/*
ReplaceProductCreated describes a response with status code 201, with default header values.

ReplaceProductCreated replace product created
*/
type ReplaceProductCreated struct {
}

// IsSuccess returns true when this replace product created response has a 2xx status code
func (o *ReplaceProductCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this replace product created response has a 3xx status code
func (o *ReplaceProductCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replace product created response has a 4xx status code
func (o *ReplaceProductCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this replace product created response has a 5xx status code
func (o *ReplaceProductCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this replace product created response a status code equal to that given
func (o *ReplaceProductCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the replace product created response
func (o *ReplaceProductCreated) Code() int {
	return 201
}

func (o *ReplaceProductCreated) Error() string {
	return fmt.Sprintf("[PUT /products/{id}][%d] replaceProductCreated ", 201)
}

func (o *ReplaceProductCreated) String() string {
	return fmt.Sprintf("[PUT /products/{id}][%d] replaceProductCreated ", 201)
}

func (o *ReplaceProductCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
